// ─────────────────────────────────────────────────────────────────────────────
// TechForge PC Builder – Verified Hardware Component Database
// Accurately sourced specifications with market indicative pricing (INR & USD)
// ─────────────────────────────────────────────────────────────────────────────

import {
  CPUComponent,
  GPUComponent,
  MotherboardComponent,
  RAMComponent,
  StorageComponent,
  PSUComponent,
  CaseComponent,
  CoolerComponent,
  AnyComponent,
  ComponentCategory,
  BuildPreset,
} from '@/types/pc-builder'

// ---------------------------------------------------------------------------
// CPUs (Processors)
// ---------------------------------------------------------------------------
export const CPUS: CPUComponent[] = [
  {
    id: 'cpu-r7-7800x3d',
    name: 'AMD Ryzen 7 7800X3D',
    brand: 'AMD',
    category: 'cpu',
    socket: 'AM5',
    cores: 8,
    threads: 16,
    baseClockGhz: 4.2,
    boostClockGhz: 5.0,
    tdpWatts: 120,
    peakPowerWatts: 135,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR5'],
    l3CacheMb: 96,
    singleThreadScore: 92,
    multiThreadScore: 88,
    tier: 'enthusiast',
    priceInr: 37999,
    priceUsd: 419,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cpu-r5-7600x',
    name: 'AMD Ryzen 5 7600X',
    brand: 'AMD',
    category: 'cpu',
    socket: 'AM5',
    cores: 6,
    threads: 12,
    baseClockGhz: 4.7,
    boostClockGhz: 5.3,
    tdpWatts: 105,
    peakPowerWatts: 130,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR5'],
    l3CacheMb: 32,
    singleThreadScore: 86,
    multiThreadScore: 74,
    tier: 'mid',
    priceInr: 18999,
    priceUsd: 209,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'cpu-r7-9700x',
    name: 'AMD Ryzen 7 9700X',
    brand: 'AMD',
    category: 'cpu',
    socket: 'AM5',
    cores: 8,
    threads: 16,
    baseClockGhz: 3.8,
    boostClockGhz: 5.5,
    tdpWatts: 65,
    peakPowerWatts: 88,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR5'],
    l3CacheMb: 32,
    singleThreadScore: 95,
    multiThreadScore: 90,
    tier: 'high',
    priceInr: 32499,
    priceUsd: 359,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'cpu-r9-7950x3d',
    name: 'AMD Ryzen 9 7950X3D',
    brand: 'AMD',
    category: 'cpu',
    socket: 'AM5',
    cores: 16,
    threads: 32,
    baseClockGhz: 4.2,
    boostClockGhz: 5.7,
    tdpWatts: 120,
    peakPowerWatts: 162,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR5'],
    l3CacheMb: 128,
    singleThreadScore: 96,
    multiThreadScore: 98,
    tier: 'enthusiast',
    priceInr: 54999,
    priceUsd: 629,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cpu-r5-5600x',
    name: 'AMD Ryzen 5 5600X',
    brand: 'AMD',
    category: 'cpu',
    socket: 'AM4',
    cores: 6,
    threads: 12,
    baseClockGhz: 3.7,
    boostClockGhz: 4.6,
    tdpWatts: 65,
    peakPowerWatts: 76,
    integratedGpu: false,
    pcieGen: 4,
    supportedRamGen: ['DDR4'],
    l3CacheMb: 32,
    singleThreadScore: 72,
    multiThreadScore: 62,
    tier: 'entry',
    priceInr: 11499,
    priceUsd: 129,
    releaseYear: 2020,
    verifiedSpec: true,
  },
  {
    id: 'cpu-r7-5700x3d',
    name: 'AMD Ryzen 7 5700X3D',
    brand: 'AMD',
    category: 'cpu',
    socket: 'AM4',
    cores: 8,
    threads: 16,
    baseClockGhz: 3.0,
    boostClockGhz: 4.1,
    tdpWatts: 105,
    peakPowerWatts: 115,
    integratedGpu: false,
    pcieGen: 4,
    supportedRamGen: ['DDR4'],
    l3CacheMb: 96,
    singleThreadScore: 78,
    multiThreadScore: 76,
    tier: 'mid',
    priceInr: 19999,
    priceUsd: 219,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'cpu-i5-13400f',
    name: 'Intel Core i5-13400F',
    brand: 'Intel',
    category: 'cpu',
    socket: 'LGA1700',
    cores: 10,
    threads: 16,
    baseClockGhz: 2.5,
    boostClockGhz: 4.6,
    tdpWatts: 65,
    peakPowerWatts: 148,
    integratedGpu: false,
    pcieGen: 5,
    supportedRamGen: ['DDR4', 'DDR5'],
    l3CacheMb: 20,
    singleThreadScore: 76,
    multiThreadScore: 72,
    tier: 'mid',
    priceInr: 16499,
    priceUsd: 185,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cpu-i5-14600k',
    name: 'Intel Core i5-14600K',
    brand: 'Intel',
    category: 'cpu',
    socket: 'LGA1700',
    cores: 14,
    threads: 20,
    baseClockGhz: 3.5,
    boostClockGhz: 5.3,
    tdpWatts: 125,
    peakPowerWatts: 181,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR4', 'DDR5'],
    l3CacheMb: 24,
    singleThreadScore: 89,
    multiThreadScore: 86,
    tier: 'high',
    priceInr: 27999,
    priceUsd: 309,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cpu-i7-14700k',
    name: 'Intel Core i7-14700K',
    brand: 'Intel',
    category: 'cpu',
    socket: 'LGA1700',
    cores: 20,
    threads: 28,
    baseClockGhz: 3.4,
    boostClockGhz: 5.6,
    tdpWatts: 125,
    peakPowerWatts: 253,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR4', 'DDR5'],
    l3CacheMb: 33,
    singleThreadScore: 94,
    multiThreadScore: 95,
    tier: 'high',
    priceInr: 37999,
    priceUsd: 409,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cpu-i9-14900k',
    name: 'Intel Core i9-14900K',
    brand: 'Intel',
    category: 'cpu',
    socket: 'LGA1700',
    cores: 24,
    threads: 32,
    baseClockGhz: 3.2,
    boostClockGhz: 6.0,
    tdpWatts: 125,
    peakPowerWatts: 253,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR4', 'DDR5'],
    l3CacheMb: 36,
    singleThreadScore: 98,
    multiThreadScore: 99,
    tier: 'enthusiast',
    priceInr: 51999,
    priceUsd: 549,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cpu-i3-12100f',
    name: 'Intel Core i3-12100F',
    brand: 'Intel',
    category: 'cpu',
    socket: 'LGA1700',
    cores: 4,
    threads: 8,
    baseClockGhz: 3.3,
    boostClockGhz: 4.3,
    tdpWatts: 58,
    peakPowerWatts: 89,
    integratedGpu: false,
    pcieGen: 5,
    supportedRamGen: ['DDR4', 'DDR5'],
    l3CacheMb: 12,
    singleThreadScore: 68,
    multiThreadScore: 50,
    tier: 'entry',
    priceInr: 7499,
    priceUsd: 84,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'cpu-ultra7-265k',
    name: 'Intel Core Ultra 7 265K',
    brand: 'Intel',
    category: 'cpu',
    socket: 'LGA1851',
    cores: 20,
    threads: 20,
    baseClockGhz: 3.9,
    boostClockGhz: 5.5,
    tdpWatts: 125,
    peakPowerWatts: 250,
    integratedGpu: true,
    pcieGen: 5,
    supportedRamGen: ['DDR5'],
    l3CacheMb: 30,
    singleThreadScore: 95,
    multiThreadScore: 94,
    tier: 'enthusiast',
    priceInr: 39999,
    priceUsd: 439,
    releaseYear: 2024,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// GPUs (Graphics Cards)
// ---------------------------------------------------------------------------
export const GPUS: GPUComponent[] = [
  {
    id: 'gpu-rtx-4090',
    name: 'NVIDIA GeForce RTX 4090 24GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 24,
    vramType: 'GDDR6X',
    lengthMm: 304,
    slotWidth: 3.5,
    tdpWatts: 450,
    recommendedPsuWatts: 850,
    pcieGen: 4,
    rasterScore1080p: 99,
    rasterScore1440p: 100,
    rasterScore4k: 100,
    rayTracingScore: 100,
    tier: 'enthusiast',
    priceInr: 174999,
    priceUsd: 1799,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rtx-4080-super',
    name: 'NVIDIA GeForce RTX 4080 Super 16GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 16,
    vramType: 'GDDR6X',
    lengthMm: 310,
    slotWidth: 3.0,
    tdpWatts: 320,
    recommendedPsuWatts: 750,
    pcieGen: 4,
    rasterScore1080p: 95,
    rasterScore1440p: 93,
    rasterScore4k: 88,
    rayTracingScore: 92,
    tier: 'enthusiast',
    priceInr: 102999,
    priceUsd: 999,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rtx-4070-ti-super',
    name: 'NVIDIA GeForce RTX 4070 Ti Super 16GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 16,
    vramType: 'GDDR6X',
    lengthMm: 285,
    slotWidth: 2.5,
    tdpWatts: 285,
    recommendedPsuWatts: 700,
    pcieGen: 4,
    rasterScore1080p: 90,
    rasterScore1440p: 86,
    rasterScore4k: 78,
    rayTracingScore: 84,
    tier: 'high',
    priceInr: 81999,
    priceUsd: 799,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rtx-4070-super',
    name: 'NVIDIA GeForce RTX 4070 Super 12GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 12,
    vramType: 'GDDR6X',
    lengthMm: 242,
    slotWidth: 2.0,
    tdpWatts: 220,
    recommendedPsuWatts: 650,
    pcieGen: 4,
    rasterScore1080p: 86,
    rasterScore1440p: 80,
    rasterScore4k: 69,
    rayTracingScore: 78,
    tier: 'high',
    priceInr: 61999,
    priceUsd: 599,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rtx-4060-ti-16gb',
    name: 'NVIDIA GeForce RTX 4060 Ti 16GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 16,
    vramType: 'GDDR6',
    lengthMm: 242,
    slotWidth: 2.0,
    tdpWatts: 165,
    recommendedPsuWatts: 550,
    pcieGen: 4,
    rasterScore1080p: 75,
    rasterScore1440p: 66,
    rasterScore4k: 52,
    rayTracingScore: 65,
    tier: 'mid',
    priceInr: 44999,
    priceUsd: 449,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rtx-4060-8gb',
    name: 'NVIDIA GeForce RTX 4060 8GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 8,
    vramType: 'GDDR6',
    lengthMm: 210,
    slotWidth: 2.0,
    tdpWatts: 115,
    recommendedPsuWatts: 500,
    pcieGen: 4,
    rasterScore1080p: 68,
    rasterScore1440p: 55,
    rasterScore4k: 40,
    rayTracingScore: 56,
    tier: 'mid',
    priceInr: 28999,
    priceUsd: 299,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rtx-3060-12gb',
    name: 'NVIDIA GeForce RTX 3060 12GB',
    brand: 'NVIDIA',
    category: 'gpu',
    chipmaker: 'NVIDIA',
    vramGb: 12,
    vramType: 'GDDR6',
    lengthMm: 200,
    slotWidth: 2.0,
    tdpWatts: 170,
    recommendedPsuWatts: 550,
    pcieGen: 4,
    rasterScore1080p: 58,
    rasterScore1440p: 46,
    rasterScore4k: 32,
    rayTracingScore: 45,
    tier: 'entry',
    priceInr: 24499,
    priceUsd: 269,
    releaseYear: 2021,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rx-7900-xtx',
    name: 'AMD Radeon RX 7900 XTX 24GB',
    brand: 'AMD',
    category: 'gpu',
    chipmaker: 'AMD',
    vramGb: 24,
    vramType: 'GDDR6',
    lengthMm: 287,
    slotWidth: 2.5,
    tdpWatts: 355,
    recommendedPsuWatts: 800,
    pcieGen: 4,
    rasterScore1080p: 96,
    rasterScore1440p: 95,
    rasterScore4k: 92,
    rayTracingScore: 78,
    tier: 'enthusiast',
    priceInr: 96999,
    priceUsd: 929,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rx-7800-xt',
    name: 'AMD Radeon RX 7800 XT 16GB',
    brand: 'AMD',
    category: 'gpu',
    chipmaker: 'AMD',
    vramGb: 16,
    vramType: 'GDDR6',
    lengthMm: 267,
    slotWidth: 2.5,
    tdpWatts: 263,
    recommendedPsuWatts: 700,
    pcieGen: 4,
    rasterScore1080p: 85,
    rasterScore1440p: 81,
    rasterScore4k: 68,
    rayTracingScore: 64,
    tier: 'high',
    priceInr: 51999,
    priceUsd: 499,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rx-7700-xt',
    name: 'AMD Radeon RX 7700 XT 12GB',
    brand: 'AMD',
    category: 'gpu',
    chipmaker: 'AMD',
    vramGb: 12,
    vramType: 'GDDR6',
    lengthMm: 267,
    slotWidth: 2.5,
    tdpWatts: 245,
    recommendedPsuWatts: 650,
    pcieGen: 4,
    rasterScore1080p: 78,
    rasterScore1440p: 71,
    rasterScore4k: 56,
    rayTracingScore: 54,
    tier: 'mid',
    priceInr: 41499,
    priceUsd: 399,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'gpu-rx-6600-8gb',
    name: 'AMD Radeon RX 6600 8GB',
    brand: 'AMD',
    category: 'gpu',
    chipmaker: 'AMD',
    vramGb: 8,
    vramType: 'GDDR6',
    lengthMm: 200,
    slotWidth: 2.0,
    tdpWatts: 132,
    recommendedPsuWatts: 450,
    pcieGen: 4,
    rasterScore1080p: 52,
    rasterScore1440p: 38,
    rasterScore4k: 24,
    rayTracingScore: 28,
    tier: 'entry',
    priceInr: 18999,
    priceUsd: 199,
    releaseYear: 2021,
    verifiedSpec: true,
  },
  {
    id: 'gpu-arc-b580',
    name: 'Intel Arc B580 12GB (Battlemage)',
    brand: 'Intel',
    category: 'gpu',
    chipmaker: 'Intel',
    vramGb: 12,
    vramType: 'GDDR6',
    lengthMm: 250,
    slotWidth: 2.0,
    tdpWatts: 190,
    recommendedPsuWatts: 550,
    pcieGen: 4,
    rasterScore1080p: 70,
    rasterScore1440p: 58,
    rasterScore4k: 42,
    rayTracingScore: 66,
    tier: 'mid',
    priceInr: 25999,
    priceUsd: 249,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'gpu-arc-a770-16gb',
    name: 'Intel Arc A770 16GB',
    brand: 'Intel',
    category: 'gpu',
    chipmaker: 'Intel',
    vramGb: 16,
    vramType: 'GDDR6',
    lengthMm: 267,
    slotWidth: 2.0,
    tdpWatts: 225,
    recommendedPsuWatts: 600,
    pcieGen: 4,
    rasterScore1080p: 67,
    rasterScore1440p: 57,
    rasterScore4k: 43,
    rayTracingScore: 62,
    tier: 'mid',
    priceInr: 27999,
    priceUsd: 289,
    releaseYear: 2022,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// Motherboards
// ---------------------------------------------------------------------------
export const MOTHERBOARDS: MotherboardComponent[] = [
  {
    id: 'mb-msi-b650-tomahawk',
    name: 'MSI MAG B650 TOMAHAWK WIFI',
    brand: 'MSI',
    category: 'motherboard',
    socket: 'AM5',
    chipset: 'B650',
    formFactor: 'ATX',
    ramGen: 'DDR5',
    ramSlots: 4,
    maxRamGb: 192,
    m2Slots: 3,
    sataPorts: 6,
    pcieGen: 4,
    wifiIncluded: true,
    basePowerDrawWatts: 45,
    tier: 'high',
    priceInr: 21999,
    priceUsd: 219,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'mb-gigabyte-b650m-ds3h',
    name: 'GIGABYTE B650M DS3H',
    brand: 'Gigabyte',
    category: 'motherboard',
    socket: 'AM5',
    chipset: 'B650',
    formFactor: 'Micro-ATX',
    ramGen: 'DDR5',
    ramSlots: 4,
    maxRamGb: 192,
    m2Slots: 2,
    sataPorts: 4,
    pcieGen: 4,
    wifiIncluded: false,
    basePowerDrawWatts: 35,
    tier: 'mid',
    priceInr: 13499,
    priceUsd: 139,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'mb-asrock-b650i-lightning',
    name: 'ASRock B650I Lightning WiFi',
    brand: 'ASRock',
    category: 'motherboard',
    socket: 'AM5',
    chipset: 'B650',
    formFactor: 'Mini-ITX',
    ramGen: 'DDR5',
    ramSlots: 2,
    maxRamGb: 96,
    m2Slots: 2,
    sataPorts: 2,
    pcieGen: 4,
    wifiIncluded: true,
    basePowerDrawWatts: 30,
    tier: 'high',
    priceInr: 20499,
    priceUsd: 199,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'mb-asus-rog-strix-x670e-e',
    name: 'ASUS ROG STRIX X670E-E GAMING WIFI',
    brand: 'ASUS',
    category: 'motherboard',
    socket: 'AM5',
    chipset: 'X670E',
    formFactor: 'ATX',
    ramGen: 'DDR5',
    ramSlots: 4,
    maxRamGb: 192,
    m2Slots: 4,
    sataPorts: 4,
    pcieGen: 5,
    wifiIncluded: true,
    basePowerDrawWatts: 55,
    tier: 'enthusiast',
    priceInr: 46999,
    priceUsd: 489,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'mb-asus-rog-strix-z790-e',
    name: 'ASUS ROG STRIX Z790-E GAMING WIFI II',
    brand: 'ASUS',
    category: 'motherboard',
    socket: 'LGA1700',
    chipset: 'Z790',
    formFactor: 'ATX',
    ramGen: 'DDR5',
    ramSlots: 4,
    maxRamGb: 192,
    m2Slots: 5,
    sataPorts: 4,
    pcieGen: 5,
    wifiIncluded: true,
    basePowerDrawWatts: 55,
    tier: 'enthusiast',
    priceInr: 44999,
    priceUsd: 469,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'mb-msi-pro-b760m-a-wifi-d4',
    name: 'MSI PRO B760M-A WIFI DDR4',
    brand: 'MSI',
    category: 'motherboard',
    socket: 'LGA1700',
    chipset: 'B760',
    formFactor: 'Micro-ATX',
    ramGen: 'DDR4',
    ramSlots: 4,
    maxRamGb: 128,
    m2Slots: 2,
    sataPorts: 4,
    pcieGen: 4,
    wifiIncluded: true,
    basePowerDrawWatts: 40,
    tier: 'mid',
    priceInr: 14499,
    priceUsd: 149,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'mb-gigabyte-b760-gaming-x-ax',
    name: 'GIGABYTE B760 GAMING X AX DDR5',
    brand: 'Gigabyte',
    category: 'motherboard',
    socket: 'LGA1700',
    chipset: 'B760',
    formFactor: 'ATX',
    ramGen: 'DDR5',
    ramSlots: 4,
    maxRamGb: 192,
    m2Slots: 3,
    sataPorts: 4,
    pcieGen: 4,
    wifiIncluded: true,
    basePowerDrawWatts: 45,
    tier: 'mid',
    priceInr: 17999,
    priceUsd: 179,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'mb-asus-prime-b760m-k-d4',
    name: 'ASUS PRIME B760M-K D4',
    brand: 'ASUS',
    category: 'motherboard',
    socket: 'LGA1700',
    chipset: 'B760',
    formFactor: 'Micro-ATX',
    ramGen: 'DDR4',
    ramSlots: 2,
    maxRamGb: 64,
    m2Slots: 2,
    sataPorts: 4,
    pcieGen: 4,
    wifiIncluded: false,
    basePowerDrawWatts: 30,
    tier: 'entry',
    priceInr: 9499,
    priceUsd: 99,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'mb-msi-b550-a-pro',
    name: 'MSI B550-A PRO',
    brand: 'MSI',
    category: 'motherboard',
    socket: 'AM4',
    chipset: 'B550',
    formFactor: 'ATX',
    ramGen: 'DDR4',
    ramSlots: 4,
    maxRamGb: 128,
    m2Slots: 2,
    sataPorts: 6,
    pcieGen: 4,
    wifiIncluded: false,
    basePowerDrawWatts: 35,
    tier: 'mid',
    priceInr: 10999,
    priceUsd: 119,
    releaseYear: 2020,
    verifiedSpec: true,
  },
  {
    id: 'mb-gigabyte-b550m-ds3h-ac',
    name: 'GIGABYTE B550M DS3H AC',
    brand: 'Gigabyte',
    category: 'motherboard',
    socket: 'AM4',
    chipset: 'B550',
    formFactor: 'Micro-ATX',
    ramGen: 'DDR4',
    ramSlots: 4,
    maxRamGb: 128,
    m2Slots: 2,
    sataPorts: 4,
    pcieGen: 4,
    wifiIncluded: true,
    basePowerDrawWatts: 30,
    tier: 'entry',
    priceInr: 8999,
    priceUsd: 95,
    releaseYear: 2020,
    verifiedSpec: true,
  },
  {
    id: 'mb-asus-z890-hero',
    name: 'ASUS ROG MAXIMUS Z890 HERO',
    brand: 'ASUS',
    category: 'motherboard',
    socket: 'LGA1851',
    chipset: 'Z890',
    formFactor: 'ATX',
    ramGen: 'DDR5',
    ramSlots: 4,
    maxRamGb: 192,
    m2Slots: 6,
    sataPorts: 4,
    pcieGen: 5,
    wifiIncluded: true,
    basePowerDrawWatts: 60,
    tier: 'enthusiast',
    priceInr: 68999,
    priceUsd: 699,
    releaseYear: 2024,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// RAM (Memory)
// ---------------------------------------------------------------------------
export const RAMS: RAMComponent[] = [
  {
    id: 'ram-corsair-vengeance-32gb-ddr5-6000',
    name: 'Corsair Vengeance 32GB (2x16GB) DDR5-6000 CL30',
    brand: 'Corsair',
    category: 'ram',
    gen: 'DDR5',
    capacityGb: 32,
    speedMhz: 6000,
    modulesCount: 2,
    casLatency: 30,
    rgb: false,
    tier: 'high',
    priceInr: 10499,
    priceUsd: 115,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ram-gskill-trident-z5-rgb-32gb-ddr5-6400',
    name: 'G.Skill Trident Z5 RGB 32GB (2x16GB) DDR5-6400 CL32',
    brand: 'G.Skill',
    category: 'ram',
    gen: 'DDR5',
    capacityGb: 32,
    speedMhz: 6400,
    modulesCount: 2,
    casLatency: 32,
    rgb: true,
    tier: 'enthusiast',
    priceInr: 13999,
    priceUsd: 145,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ram-kingston-fury-beast-16gb-ddr5-5600',
    name: 'Kingston Fury Beast 16GB (1x16GB) DDR5-5600 CL36',
    brand: 'Kingston',
    category: 'ram',
    gen: 'DDR5',
    capacityGb: 16,
    speedMhz: 5600,
    modulesCount: 1,
    casLatency: 36,
    rgb: false,
    tier: 'mid',
    priceInr: 4999,
    priceUsd: 55,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ram-crucial-pro-64gb-ddr5-5600',
    name: 'Crucial Pro 64GB (2x32GB) DDR5-5600 CL46',
    brand: 'Crucial',
    category: 'ram',
    gen: 'DDR5',
    capacityGb: 64,
    speedMhz: 5600,
    modulesCount: 2,
    casLatency: 46,
    rgb: false,
    tier: 'enthusiast',
    priceInr: 18999,
    priceUsd: 199,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ram-teamgroup-tforce-32gb-ddr5-6000',
    name: 'TeamGroup T-Force Delta RGB 32GB (2x16GB) DDR5-6000 CL30',
    brand: 'TeamGroup',
    category: 'ram',
    gen: 'DDR5',
    capacityGb: 32,
    speedMhz: 6000,
    modulesCount: 2,
    casLatency: 30,
    rgb: true,
    tier: 'high',
    priceInr: 11499,
    priceUsd: 120,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ram-corsair-vengeance-lpx-16gb-ddr4-3200',
    name: 'Corsair Vengeance LPX 16GB (2x8GB) DDR4-3200 CL16',
    brand: 'Corsair',
    category: 'ram',
    gen: 'DDR4',
    capacityGb: 16,
    speedMhz: 3200,
    modulesCount: 2,
    casLatency: 16,
    rgb: false,
    tier: 'entry',
    priceInr: 3499,
    priceUsd: 39,
    releaseYear: 2019,
    verifiedSpec: true,
  },
  {
    id: 'ram-gskill-ripjaws-v-32gb-ddr4-3600',
    name: 'G.Skill Ripjaws V 32GB (2x16GB) DDR4-3600 CL18',
    brand: 'G.Skill',
    category: 'ram',
    gen: 'DDR4',
    capacityGb: 32,
    speedMhz: 3600,
    modulesCount: 2,
    casLatency: 18,
    rgb: false,
    tier: 'mid',
    priceInr: 6499,
    priceUsd: 69,
    releaseYear: 2020,
    verifiedSpec: true,
  },
  {
    id: 'ram-kingston-fury-beast-32gb-ddr4-3200',
    name: 'Kingston Fury Beast RGB 32GB (2x16GB) DDR4-3200 CL16',
    brand: 'Kingston',
    category: 'ram',
    gen: 'DDR4',
    capacityGb: 32,
    speedMhz: 3200,
    modulesCount: 2,
    casLatency: 16,
    rgb: true,
    tier: 'mid',
    priceInr: 7299,
    priceUsd: 78,
    releaseYear: 2021,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// Storage (NVMe, SATA SSD, HDD)
// ---------------------------------------------------------------------------
export const STORAGES: StorageComponent[] = [
  {
    id: 'ssd-samsung-990-pro-2tb',
    name: 'Samsung 990 Pro 2TB NVMe M.2 SSD',
    brand: 'Samsung',
    category: 'storage',
    type: 'NVMe SSD',
    interface: 'M.2 PCIe 4.0 x4',
    capacityGb: 2000,
    readSpeedMbps: 7450,
    writeSpeedMbps: 6900,
    isM2: true,
    tier: 'enthusiast',
    priceInr: 16999,
    priceUsd: 179,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ssd-samsung-990-pro-1tb',
    name: 'Samsung 990 Pro 1TB NVMe M.2 SSD',
    brand: 'Samsung',
    category: 'storage',
    type: 'NVMe SSD',
    interface: 'M.2 PCIe 4.0 x4',
    capacityGb: 1000,
    readSpeedMbps: 7450,
    writeSpeedMbps: 6900,
    isM2: true,
    tier: 'high',
    priceInr: 9999,
    priceUsd: 109,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ssd-wd-black-sn850x-1tb',
    name: 'WD Black SN850X 1TB NVMe M.2 SSD',
    brand: 'Western Digital',
    category: 'storage',
    type: 'NVMe SSD',
    interface: 'M.2 PCIe 4.0 x4',
    capacityGb: 1000,
    readSpeedMbps: 7300,
    writeSpeedMbps: 6300,
    isM2: true,
    tier: 'high',
    priceInr: 8799,
    priceUsd: 94,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'ssd-crucial-p3-plus-1tb',
    name: 'Crucial P3 Plus 1TB NVMe M.2 SSD',
    brand: 'Crucial',
    category: 'storage',
    type: 'NVMe SSD',
    interface: 'M.2 PCIe 4.0 x4',
    capacityGb: 1000,
    readSpeedMbps: 5000,
    writeSpeedMbps: 3600,
    isM2: true,
    tier: 'mid',
    priceInr: 5899,
    priceUsd: 62,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'ssd-crucial-t700-2tb-gen5',
    name: 'Crucial T700 2TB PCIe 5.0 NVMe SSD (Heatsink)',
    brand: 'Crucial',
    category: 'storage',
    type: 'NVMe SSD',
    interface: 'M.2 PCIe 5.0 x4',
    capacityGb: 2000,
    readSpeedMbps: 12400,
    writeSpeedMbps: 11800,
    isM2: true,
    tier: 'enthusiast',
    priceInr: 28999,
    priceUsd: 299,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'ssd-crucial-mx500-1tb-sata',
    name: 'Crucial MX500 1TB 2.5" SATA III SSD',
    brand: 'Crucial',
    category: 'storage',
    type: 'SATA SSD',
    interface: 'SATA III',
    capacityGb: 1000,
    readSpeedMbps: 560,
    writeSpeedMbps: 510,
    isM2: false,
    tier: 'entry',
    priceInr: 5499,
    priceUsd: 59,
    releaseYear: 2018,
    verifiedSpec: true,
  },
  {
    id: 'hdd-seagate-barracuda-2tb',
    name: 'Seagate Barracuda 2TB 7200RPM HDD',
    brand: 'Seagate',
    category: 'storage',
    type: 'HDD',
    interface: 'SATA III',
    capacityGb: 2000,
    readSpeedMbps: 190,
    writeSpeedMbps: 180,
    isM2: false,
    tier: 'entry',
    priceInr: 4999,
    priceUsd: 54,
    releaseYear: 2018,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// Power Supply Units (PSU)
// ---------------------------------------------------------------------------
export const PSUS: PSUComponent[] = [
  {
    id: 'psu-corsair-rm850x',
    name: 'Corsair RM850x (2021) 850W Gold',
    brand: 'Corsair',
    category: 'psu',
    wattage: 850,
    efficiency: '80+ Gold',
    modularity: 'Full',
    formFactor: 'ATX',
    pcieConnectorsCount: 4,
    atx3Compatible: false,
    tier: 'enthusiast',
    priceInr: 12499,
    priceUsd: 139,
    releaseYear: 2021,
    verifiedSpec: true,
  },
  {
    id: 'psu-corsair-rm750e-atx3',
    name: 'Corsair RM750e (2023) 750W Gold ATX 3.0',
    brand: 'Corsair',
    category: 'psu',
    wattage: 750,
    efficiency: '80+ Gold',
    modularity: 'Full',
    formFactor: 'ATX',
    pcieConnectorsCount: 3,
    atx3Compatible: true,
    tier: 'high',
    priceInr: 9499,
    priceUsd: 99,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'psu-corsair-rm1000e-atx3',
    name: 'Corsair RM1000e (2023) 1000W Gold ATX 3.0',
    brand: 'Corsair',
    category: 'psu',
    wattage: 1000,
    efficiency: '80+ Gold',
    modularity: 'Full',
    formFactor: 'ATX',
    pcieConnectorsCount: 4,
    atx3Compatible: true,
    tier: 'enthusiast',
    priceInr: 15999,
    priceUsd: 169,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'psu-seasonic-focus-gx-850',
    name: 'Seasonic Focus GX-850 850W Gold',
    brand: 'Seasonic',
    category: 'psu',
    wattage: 850,
    efficiency: '80+ Gold',
    modularity: 'Full',
    formFactor: 'ATX',
    pcieConnectorsCount: 4,
    atx3Compatible: true,
    tier: 'high',
    priceInr: 13499,
    priceUsd: 145,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'psu-msi-mag-a650bn',
    name: 'MSI MAG A650BN 650W Bronze',
    brand: 'MSI',
    category: 'psu',
    wattage: 650,
    efficiency: '80+ Bronze',
    modularity: 'Non-Modular',
    formFactor: 'ATX',
    pcieConnectorsCount: 2,
    atx3Compatible: false,
    tier: 'mid',
    priceInr: 4799,
    priceUsd: 54,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'psu-deepcool-pk550d',
    name: 'Deepcool PK550D 550W Bronze',
    brand: 'Deepcool',
    category: 'psu',
    wattage: 550,
    efficiency: '80+ Bronze',
    modularity: 'Non-Modular',
    formFactor: 'ATX',
    pcieConnectorsCount: 2,
    atx3Compatible: false,
    tier: 'entry',
    priceInr: 3499,
    priceUsd: 39,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'psu-corsair-sf750-sfx',
    name: 'Corsair SF750 750W Platinum SFX',
    brand: 'Corsair',
    category: 'psu',
    wattage: 750,
    efficiency: '80+ Platinum',
    modularity: 'Full',
    formFactor: 'SFX',
    pcieConnectorsCount: 4,
    atx3Compatible: false,
    tier: 'enthusiast',
    priceInr: 15499,
    priceUsd: 169,
    releaseYear: 2020,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// Cases (Chassis)
// ---------------------------------------------------------------------------
export const CASES: CaseComponent[] = [
  {
    id: 'case-lian-li-o11d-evo',
    name: 'Lian Li O11 Dynamic EVO',
    brand: 'Lian Li',
    category: 'case',
    formFactor: 'ATX Mid Tower',
    maxGpuLengthMm: 426,
    maxCoolerHeightMm: 167,
    radiatorSupportMm: [120, 240, 280, 360],
    supportedMotherboards: ['ATX', 'Micro-ATX', 'Mini-ITX', 'E-ATX'],
    includedFansCount: 0,
    sidePanel: 'Tempered Glass',
    tier: 'enthusiast',
    priceInr: 14499,
    priceUsd: 159,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'case-corsair-4000d-airflow',
    name: 'Corsair 4000D Airflow',
    brand: 'Corsair',
    category: 'case',
    formFactor: 'ATX Mid Tower',
    maxGpuLengthMm: 360,
    maxCoolerHeightMm: 170,
    radiatorSupportMm: [120, 240, 280, 360],
    supportedMotherboards: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    includedFansCount: 2,
    sidePanel: 'Tempered Glass',
    tier: 'high',
    priceInr: 7999,
    priceUsd: 89,
    releaseYear: 2020,
    verifiedSpec: true,
  },
  {
    id: 'case-nzxt-h5-flow',
    name: 'NZXT H5 Flow (2024)',
    brand: 'NZXT',
    category: 'case',
    formFactor: 'ATX Mid Tower',
    maxGpuLengthMm: 365,
    maxCoolerHeightMm: 165,
    radiatorSupportMm: [120, 240, 280],
    supportedMotherboards: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    includedFansCount: 2,
    sidePanel: 'Tempered Glass',
    tier: 'mid',
    priceInr: 7499,
    priceUsd: 84,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'case-fractal-north',
    name: 'Fractal Design North (Walnut Mesh)',
    brand: 'Fractal Design',
    category: 'case',
    formFactor: 'ATX Mid Tower',
    maxGpuLengthMm: 355,
    maxCoolerHeightMm: 170,
    radiatorSupportMm: [120, 240, 280, 360],
    supportedMotherboards: ['ATX', 'Micro-ATX', 'Mini-ITX'],
    includedFansCount: 2,
    sidePanel: 'Mesh',
    tier: 'enthusiast',
    priceInr: 13999,
    priceUsd: 149,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'case-montech-air-903-max',
    name: 'Montech Air 903 Max',
    brand: 'Montech',
    category: 'case',
    formFactor: 'ATX Mid Tower',
    maxGpuLengthMm: 400,
    maxCoolerHeightMm: 180,
    radiatorSupportMm: [120, 240, 280, 360],
    supportedMotherboards: ['ATX', 'Micro-ATX', 'Mini-ITX', 'E-ATX'],
    includedFansCount: 4,
    sidePanel: 'Tempered Glass',
    tier: 'mid',
    priceInr: 6499,
    priceUsd: 75,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'case-cm-q300l',
    name: 'Cooler Master MasterBox Q300L',
    brand: 'Cooler Master',
    category: 'case',
    formFactor: 'MicroATX Mini',
    maxGpuLengthMm: 360,
    maxCoolerHeightMm: 159,
    radiatorSupportMm: [120, 240],
    supportedMotherboards: ['Micro-ATX', 'Mini-ITX'],
    includedFansCount: 1,
    sidePanel: 'Tempered Glass',
    tier: 'entry',
    priceInr: 3999,
    priceUsd: 45,
    releaseYear: 2018,
    verifiedSpec: true,
  },
  {
    id: 'case-lian-li-a4-h2o',
    name: 'Lian Li A4-H2O (Small Form Factor)',
    brand: 'Lian Li',
    category: 'case',
    formFactor: 'Mini-ITX',
    maxGpuLengthMm: 322,
    maxCoolerHeightMm: 55,
    radiatorSupportMm: [120, 240],
    supportedMotherboards: ['Mini-ITX'],
    includedFansCount: 0,
    sidePanel: 'Mesh',
    tier: 'enthusiast',
    priceInr: 14999,
    priceUsd: 155,
    releaseYear: 2022,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// CPU Coolers
// ---------------------------------------------------------------------------
export const COOLERS: CoolerComponent[] = [
  {
    id: 'cooler-peerless-assassin-120-se',
    name: 'Thermalright Peerless Assassin 120 SE',
    brand: 'Thermalright',
    category: 'cooler',
    type: 'Air',
    supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    heightMm: 155,
    radiatorSizeMm: 0,
    maxTdpRatingWatts: 245,
    noiseLevelDb: 25.6,
    tier: 'mid',
    priceInr: 3499,
    priceUsd: 36,
    releaseYear: 2022,
    verifiedSpec: true,
  },
  {
    id: 'cooler-noctua-nh-d15',
    name: 'Noctua NH-D15 chromax.black',
    brand: 'Noctua',
    category: 'cooler',
    type: 'Air',
    supportedSockets: ['AM5', 'AM4', 'LGA1700'],
    heightMm: 165,
    radiatorSizeMm: 0,
    maxTdpRatingWatts: 260,
    noiseLevelDb: 24.6,
    tier: 'enthusiast',
    priceInr: 10999,
    priceUsd: 119,
    releaseYear: 2019,
    verifiedSpec: true,
  },
  {
    id: 'cooler-deepcool-ak620',
    name: 'Deepcool AK620 High-Performance Dual-Tower',
    brand: 'Deepcool',
    category: 'cooler',
    type: 'Air',
    supportedSockets: ['AM5', 'AM4', 'LGA1700'],
    heightMm: 160,
    radiatorSizeMm: 0,
    maxTdpRatingWatts: 260,
    noiseLevelDb: 28.0,
    tier: 'high',
    priceInr: 5499,
    priceUsd: 62,
    releaseYear: 2021,
    verifiedSpec: true,
  },
  {
    id: 'cooler-arctic-freezer-iii-360',
    name: 'ARCTIC Liquid Freezer III 360 AIO',
    brand: 'ARCTIC',
    category: 'cooler',
    type: 'AIO 360mm',
    supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    heightMm: 65,
    radiatorSizeMm: 360,
    maxTdpRatingWatts: 350,
    noiseLevelDb: 22.5,
    tier: 'enthusiast',
    priceInr: 10499,
    priceUsd: 110,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'cooler-arctic-freezer-iii-240',
    name: 'ARCTIC Liquid Freezer III 240 AIO',
    brand: 'ARCTIC',
    category: 'cooler',
    type: 'AIO 240mm',
    supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    heightMm: 65,
    radiatorSizeMm: 240,
    maxTdpRatingWatts: 280,
    noiseLevelDb: 22.5,
    tier: 'high',
    priceInr: 7999,
    priceUsd: 85,
    releaseYear: 2024,
    verifiedSpec: true,
  },
  {
    id: 'cooler-nzxt-kraken-elite-360-rgb',
    name: 'NZXT Kraken Elite 360 RGB with LCD',
    brand: 'NZXT',
    category: 'cooler',
    type: 'AIO 360mm',
    supportedSockets: ['AM5', 'AM4', 'LGA1700', 'LGA1851'],
    heightMm: 55,
    radiatorSizeMm: 360,
    maxTdpRatingWatts: 320,
    noiseLevelDb: 30.6,
    tier: 'enthusiast',
    priceInr: 24999,
    priceUsd: 279,
    releaseYear: 2023,
    verifiedSpec: true,
  },
  {
    id: 'cooler-assassin-x-120-se',
    name: 'Thermalright Assassin X 120 Refined SE',
    brand: 'Thermalright',
    category: 'cooler',
    type: 'Air',
    supportedSockets: ['AM5', 'AM4', 'LGA1700'],
    heightMm: 148,
    radiatorSizeMm: 0,
    maxTdpRatingWatts: 180,
    noiseLevelDb: 25.6,
    tier: 'entry',
    priceInr: 1899,
    priceUsd: 20,
    releaseYear: 2022,
    verifiedSpec: true,
  },
]

// ---------------------------------------------------------------------------
// Combined Catalog Map
// ---------------------------------------------------------------------------
export const ALL_COMPONENTS: Record<ComponentCategory, AnyComponent[]> = {
  cpu: CPUS,
  gpu: GPUS,
  motherboard: MOTHERBOARDS,
  ram: RAMS,
  storage: STORAGES,
  psu: PSUS,
  case: CASES,
  cooler: COOLERS,
}

export function findComponentById(id: string): AnyComponent | undefined {
  for (const cat of Object.keys(ALL_COMPONENTS) as ComponentCategory[]) {
    const item = ALL_COMPONENTS[cat].find((c) => c.id === id)
    if (item) return item
  }
  return undefined
}

// ---------------------------------------------------------------------------
// Hand-Curated Balanced Build Presets
// ---------------------------------------------------------------------------
export const BUILD_PRESETS: BuildPreset[] = [
  {
    id: 'preset-budget-esports-50k',
    name: 'Budget Esports Champion',
    tagline: 'High FPS 1080p competitive gaming on a realistic budget',
    targetBudgetInr: 52000,
    targetBudgetUsd: 599,
    useCase: 'Budget',
    description: 'Perfect for Valorant, CS2, Fortnite, Minecraft and GTA V at 1080p high refresh rates.',
    partIds: {
      cpu: 'cpu-r5-5600x',
      gpu: 'gpu-rx-6600-8gb',
      motherboard: 'mb-gigabyte-b550m-ds3h-ac',
      ram: 'ram-corsair-vengeance-lpx-16gb-ddr4-3200',
      storage: 'ssd-crucial-p3-plus-1tb',
      psu: 'psu-deepcool-pk550d',
      case: 'case-cm-q300l',
      cooler: 'cooler-assassin-x-120-se',
    },
  },
  {
    id: 'preset-mainstream-gaming-75k',
    name: '1080p / 1440p Sweet Spot',
    tagline: 'Unbeatable price-to-performance for AAA games and creative work',
    targetBudgetInr: 78000,
    targetBudgetUsd: 899,
    useCase: 'Gaming',
    description: 'Crushes modern games with ray tracing support, fast PCIe 4.0 storage, and efficient power draw.',
    partIds: {
      cpu: 'cpu-i5-13400f',
      gpu: 'gpu-rtx-4060-8gb',
      motherboard: 'mb-msi-pro-b760m-a-wifi-d4',
      ram: 'ram-gskill-ripjaws-v-32gb-ddr4-3600',
      storage: 'ssd-wd-black-sn850x-1tb',
      psu: 'psu-msi-mag-a650bn',
      case: 'case-montech-air-903-max',
      cooler: 'cooler-peerless-assassin-120-se',
    },
  },
  {
    id: 'preset-1440p-high-fps-150k',
    name: '1440p High-FPS Powerhouse',
    tagline: 'Next-gen AM5 platform with Ryzen 7800X3D and RTX 4070 Super',
    targetBudgetInr: 165000,
    targetBudgetUsd: 1799,
    useCase: 'Gaming',
    description: 'The definitive gaming configuration. Unmatched gaming efficiency, DDR5-6000 low latency RAM, and whisper-quiet cooling.',
    partIds: {
      cpu: 'cpu-r7-7800x3d',
      gpu: 'gpu-rtx-4070-super',
      motherboard: 'mb-msi-b650-tomahawk',
      ram: 'ram-corsair-vengeance-32gb-ddr5-6000',
      storage: 'ssd-samsung-990-pro-2tb',
      psu: 'psu-corsair-rm750e-atx3',
      case: 'case-corsair-4000d-airflow',
      cooler: 'cooler-peerless-assassin-120-se',
    },
  },
  {
    id: 'preset-creator-workstation-200k',
    name: 'Creator & 3D Studio Rig',
    tagline: 'Heavy multi-threading, 16GB VRAM, and massive Gen4 bandwidth',
    targetBudgetInr: 215000,
    targetBudgetUsd: 2299,
    useCase: 'Content Creation',
    description: 'Engineered for Blender, Premiere Pro, Unreal Engine 5, DaVinci Resolve, and high-framerate 1440p/4K gaming.',
    partIds: {
      cpu: 'cpu-i7-14700k',
      gpu: 'gpu-rtx-4070-ti-super',
      motherboard: 'mb-gigabyte-b760-gaming-x-ax',
      ram: 'ram-crucial-pro-64gb-ddr5-5600',
      storage: 'ssd-samsung-990-pro-2tb',
      psu: 'psu-corsair-rm850x',
      case: 'case-fractal-north',
      cooler: 'cooler-arctic-freezer-iii-360',
    },
  },
  {
    id: 'preset-enthusiast-4k-300k',
    name: '4K Ultra Enthusiast & AI Beast',
    tagline: 'Zero compromises: 24GB VRAM, extreme 4K ray tracing, and flagship AM5',
    targetBudgetInr: 335000,
    targetBudgetUsd: 3699,
    useCase: 'AI / Workstation',
    description: 'Tackles local LLM inference, 4K native ultra ray tracing, and simulation at maximum frame rates.',
    partIds: {
      cpu: 'cpu-r7-7800x3d',
      gpu: 'gpu-rtx-4090',
      motherboard: 'mb-asus-rog-strix-x670e-e',
      ram: 'ram-gskill-trident-z5-rgb-32gb-ddr5-6400',
      storage: 'ssd-crucial-t700-2tb-gen5',
      psu: 'psu-corsair-rm1000e-atx3',
      case: 'case-lian-li-o11d-evo',
      cooler: 'cooler-arctic-freezer-iii-360',
    },
  },
]
