import { SeoBuildPage } from '@/types/pc-builder'

export const SEO_BUILDS: SeoBuildPage[] = [
  {
    slug: 'gaming-pc-under-50000',
    title: 'Best Gaming PC Build Under ₹50,000 (2026)',
    metaTitle: 'Gaming PC Under ₹50,000 (INR) - Verified Parts, FPS & Compatibility | RigCraft',
    metaDescription:
      'The definitive budget gaming PC build under ₹50,000 in India. Genuine 6-core processor, dedicated RX 6600 8GB GPU, NVMe SSD, and 1080p high-FPS benchmarks.',
    targetBudgetInr: 49500,
    targetBudgetUsd: 600,
    categoryTag: 'Budget 1080p Esports',
    resolutionTarget: '1080p',
    primaryUseCase: 'Esports & 1080p AAA Gaming',
    headlineDescription:
      'Engineered specifically to hit 60-120+ FPS at 1080p settings in competitive titles like Fortnite, Valorant, GTA V, and CS2 while remaining strictly under the ₹50,000 budget cap.',
    partIds: {
      cpu: 'cpu-r5-5600x',
      gpu: 'gpu-rx-6600-8gb',
      motherboard: 'mb-gigabyte-b550m-ds3h-ac',
      ram: 'ram-corsair-vengeance-lpx-16gb-ddr4-3200',
      storage: 'ssd-crucial-p3-plus-1tb',
      psu: 'psu-deepcool-pk550d',
      case: 'case-cm-q300l',
      cooler: 'cooler-assassin-x-120-se',
    },
    componentRationale: {
      cpu: 'AMD Ryzen 5 5600 delivers 6 cores, 12 threads, and high IPC on AM4, preventing CPU bottlenecks in esports games.',
      gpu: 'AMD Radeon RX 7600 provides modern RDNA 3 architecture and 8GB VRAM, dominating 1080p High settings.',
      motherboard: 'Gigabyte B550M DS3H offers PCIe 4.0 lanes, dual M.2 slots, and solid VRMs for sustained gaming loads.',
      ram: '16GB (2x8GB) DDR4-3200 dual-channel kit provides optimal memory bandwidth for Infinity Fabric.',
      storage: 'Crucial P3 Plus 1TB delivers over 5,000 MB/s read speeds for rapid level loads and fast Windows boot times.',
      psu: 'Cooler Master MWE 550 Bronze provides reliable Japanese capacitors and safety protections for a ~320W system load.',
      case: 'Cooler Master Q300L keeps budget low while offering modular I/O and perforated mesh ventilation.',
      cooler: 'Thermalright Assassin X 120 SE delivers 4 copper heatpipes to keep the 65W CPU under 65°C under full load.',
    },
    upgradePaths: [
      'Upgrade to 32GB RAM down the road if running heavily modded titles or memory-heavy background tasks.',
      'Drop in a Ryzen 7 5700X3D for maximum gaming cache without changing the motherboard.',
      'Add a second M.2 NVMe SSD using the secondary onboard slot for extra game library capacity.',
    ],
    publishedDate: '2026-01-15',
    lastUpdatedDate: '2026-10-06',
  },
  {
    slug: 'gaming-pc-under-75000',
    title: 'Best Gaming PC Build Under ₹75,000 (2026)',
    metaTitle: 'Gaming PC Under ₹75,000 (INR) - 1080p Ultra & 1440p Entry | RigCraft',
    metaDescription:
      'High-performance PC configuration under ₹75,000 in India. Modern Ryzen 5 or Core i5, RTX 4060 8GB, 1TB Gen4 NVMe, and verified power balance.',
    targetBudgetInr: 74200,
    targetBudgetUsd: 890,
    categoryTag: '1080p Ultra / 1440p Entry',
    resolutionTarget: '1080p',
    primaryUseCase: 'AAA Gaming & Streaming',
    headlineDescription:
      'The sweet spot build for gamers wanting maximum visual fidelity at 1080p Ultra, DLSS 3 frame generation, and smooth 1440p entry performance.',
    partIds: {
      cpu: 'cpu-r5-7600x',
      gpu: 'gpu-rtx-4060-8gb',
      motherboard: 'mb-gigabyte-b650m-ds3h',
      ram: 'ram-corsair-vengeance-32gb-ddr5-6000',
      storage: 'ssd-wd-black-sn850x-1tb',
      psu: 'psu-msi-mag-a650bn',
      case: 'case-montech-air-903-max',
      cooler: 'cooler-peerless-assassin-120-se',
    },
    componentRationale: {
      cpu: 'Ryzen 5 7600X delivers 5.3 GHz boost clock and DDR5 support on the future-proof AM5 platform.',
      gpu: 'NVIDIA GeForce RTX 4060 features Ada Lovelace ray tracing, DLSS 3.5, and low 115W power draw.',
      motherboard: 'Gigabyte B650M DS3H supports AM5 processors with DDR5 memory up to 6400MHz+.',
      ram: '32GB DDR5-6000 CL30 memory kit ensures low latency and plenty of headroom for heavy multitasking.',
      storage: 'WD Black SN850X 1TB with DRAM cache delivers blistering 7,300 MB/s read speeds.',
      psu: 'MSI MAG A650BN provides 650W 80+ Bronze certified power delivery for peace of mind.',
      case: 'Montech Air 903 Max comes with 4 pre-installed 140mm PWM fans for high airflow right out of the box.',
      cooler: 'Thermalright Peerless Assassin 120 SE dual-tower heatsink handles sustained multi-threaded turbo clocks.',
    },
    upgradePaths: [
      'AM5 socket guarantees support for upcoming AMD CPU generations through 2027+.',
      'Drop in an RTX 4070 or 4070 Super in the future; the 650W PSU has ample headroom.',
    ],
    publishedDate: '2026-02-10',
    lastUpdatedDate: '2026-10-06',
  },
  {
    slug: 'gaming-pc-under-100000',
    title: 'Best Gaming PC Build Under ₹1,00,000 (2026)',
    metaTitle: 'Gaming PC Under ₹1 Lakh (₹1,00,000) - High-Refresh 1440p Gaming | RigCraft',
    metaDescription:
      'Sub-₹1 Lakh gaming PC configuration. Uncompromised 1440p Quad HD performance, RTX 4060 Ti / RX 7700 XT, 32GB DDR5, and ATX 3.0 power supply.',
    targetBudgetInr: 98500,
    targetBudgetUsd: 1190,
    categoryTag: '1440p High-Refresh',
    resolutionTarget: '1440p',
    primaryUseCase: '1440p High Refresh Gaming & Content Creation',
    headlineDescription:
      'Tailored for 1440p displays with 90-144+ FPS in modern titles, high VRAM bandwidth, and an upgradeable DDR5 motherboard.',
    partIds: {
      cpu: 'cpu-r5-7600x',
      gpu: 'gpu-rx-7700-xt',
      motherboard: 'mb-msi-b650-tomahawk',
      ram: 'ram-corsair-vengeance-32gb-ddr5-6000',
      storage: 'ssd-wd-black-sn850x-1tb',
      psu: 'psu-corsair-rm750e-atx3',
      case: 'case-corsair-4000d-airflow',
      cooler: 'cooler-peerless-assassin-120-se',
    },
    componentRationale: {
      cpu: 'AMD Ryzen 5 7600X balances 6 high-speed cores with low platform latency.',
      gpu: 'AMD Radeon RX 7700 XT with 12GB GDDR6 memory delivers fast 1440p rasterization.',
      motherboard: 'MSI MAG B650 Tomahawk WiFi features robust 14+2+1 power phases, Wi-Fi 6E, and reinforced PCIe slots.',
      ram: 'Corsair Vengeance 32GB DDR5-6000 CL30 provides optimum memory clocks for Ryzen 7000.',
      storage: 'WD Black SN850X 1TB PCIe 4.0 NVMe ensures immediate boot and zero game stutters.',
      psu: 'Corsair RM750e 80+ Gold certified ATX 3.0 power supply handles GPU transient power surges smoothly.',
      case: 'Corsair 4000D Airflow offers steel mesh front, cable management channels, and high clearance.',
      cooler: 'Dual-tower Peerless Assassin 120 SE maintains quiet operation and low thermal resistance.',
    },
    upgradePaths: [
      'Upgrade to Ryzen 7 7800X3D for an immediate boost in simulation and competitive titles.',
      'Drop in a 4K capable GPU later; the 750W Gold PSU has plenty of clean overhead.',
    ],
    publishedDate: '2026-03-01',
    lastUpdatedDate: '2026-10-06',
  },
  {
    slug: 'best-pc-for-1440p-gaming',
    title: 'The Ultimate 1440p Gaming PC Build (2026)',
    metaTitle: 'Best 1440p Gaming PC Build - Ryzen 7 7800X3D & RTX 4070 Super | RigCraft',
    metaDescription:
      'Engineered for maximum 1440p high-refresh gaming. Featuring the Ryzen 7 7800X3D with 3D V-Cache, RTX 4070 Super 12GB, 32GB DDR5-6000, and Samsung 990 Pro.',
    targetBudgetInr: 154000,
    targetBudgetUsd: 1850,
    categoryTag: '1440p Ultra / Competitive',
    resolutionTarget: '1440p',
    primaryUseCase: '1440p Max Settings & Ray Tracing',
    headlineDescription:
      'The gold standard of modern PC gaming. Pairs the world’s leading gaming processor with an RTX 4070 Super for blistering framerates and crystal-clear ray tracing.',
    partIds: {
      cpu: 'cpu-r7-7800x3d',
      gpu: 'gpu-rtx-4070-super',
      motherboard: 'mb-msi-b650-tomahawk',
      ram: 'ram-corsair-vengeance-32gb-ddr5-6000',
      storage: 'ssd-samsung-990-pro-2tb',
      psu: 'psu-corsair-rm750e-atx3',
      case: 'case-fractal-north',
      cooler: 'cooler-peerless-assassin-120-se',
    },
    componentRationale: {
      cpu: 'Ryzen 7 7800X3D with 96MB 3D V-Cache eliminates CPU bottlenecks, yielding high 1% low framerates.',
      gpu: 'RTX 4070 Super features 12GB GDDR6X, Ada Lovelace architecture, DLSS 3.5, and dual encoders.',
      motherboard: 'MSI B650 Tomahawk delivers reinforced PCIe steel armor and high thermal heatsinks.',
      ram: '32GB DDR5-6000 low-latency RAM maintains high bandwidth across multi-threaded gaming loops.',
      storage: 'Samsung 990 Pro 2TB delivers top-tier sequential and random 4K read performance.',
      psu: 'Corsair RM750e ATX 3.0 750W 80+ Gold provides certified efficiency and quiet zero-RPM fan mode.',
      case: 'Fractal North combines real walnut wood aesthetics with unobstructed front-to-back airflow.',
      cooler: 'Peerless Assassin 120 SE cools the 120W TDP chip with ease while maintaining low noise.',
    },
    upgradePaths: [
      'Ready for drop-in next-gen 50-series GPUs whenever desired.',
      'Supports memory expansion up to 128GB DDR5 across 4 DIMM slots.',
    ],
    publishedDate: '2026-03-15',
    lastUpdatedDate: '2026-10-06',
  },
  {
    slug: 'best-pc-for-ai-ml',
    title: 'Best PC Build for AI & Machine Learning (2026)',
    metaTitle: 'Best PC for AI & Machine Learning - CUDA, Local LLMs & PyTorch | RigCraft',
    metaDescription:
      'Optimal desktop workstation for local deep learning, LLM fine-tuning, and PyTorch. High VRAM NVIDIA GPU, 64GB DDR5 RAM, and Gen4 NVMe storage.',
    targetBudgetInr: 215000,
    targetBudgetUsd: 2590,
    categoryTag: 'AI / Data Science Workstation',
    resolutionTarget: '4K',
    primaryUseCase: 'Local LLMs, Computer Vision, PyTorch & CUDA',
    headlineDescription:
      'Configured for AI engineers and researchers. Maximizes GPU VRAM, CUDA core density, memory capacity for large tensor batches, and sustained multi-hour training thermals.',
    partIds: {
      cpu: 'cpu-i7-14700k',
      gpu: 'gpu-rtx-4070-ti-super',
      motherboard: 'mb-asus-rog-strix-z790-e',
      ram: 'ram-crucial-pro-64gb-ddr5-5600',
      storage: 'ssd-samsung-990-pro-2tb',
      psu: 'psu-corsair-rm850x',
      case: 'case-lian-li-o11d-evo',
      cooler: 'cooler-arctic-freezer-iii-360',
    },
    componentRationale: {
      cpu: 'Intel Core i7-14700K with 20 cores (8P + 12E) and 28 threads speeds through data preprocessing and tokenization.',
      gpu: 'RTX 4070 Ti Super packs 16GB GDDR6X on a 256-bit bus, crucial for fitting 7B-13B parameter quantized LLMs in memory.',
      motherboard: 'ASUS TUF Gaming Z790-Plus WiFi features 16+1 DrMOS power stages and quadruple M.2 slots.',
      ram: '64GB (2x32GB) DDR5 provides vast system memory for Pandas dataframes and training datasets.',
      storage: 'Samsung 990 Pro 2TB loads multi-gigabyte dataset shards with maximum I/O throughput.',
      psu: 'Corsair RM850x with 100% Japanese capacitors handles high continuous compute draw during long training epochs.',
      case: 'Lian Li O11 Dynamic EVO allows triple 360mm radiator placements for continuous heat dissipation.',
      cooler: 'Arctic Liquid Freezer III 360 AIO with integrated VRM fan keeps CPU cold during heavy compile passes.',
    },
    upgradePaths: [
      'Expandable to 128GB or 192GB DDR5 RAM for extra-large dataset in-memory manipulation.',
      'Supports secondary GPU installation via PCIe x16 slot for multi-GPU inference.',
    ],
    publishedDate: '2026-03-20',
    lastUpdatedDate: '2026-10-06',
  },
  {
    slug: 'best-pc-for-programming',
    title: 'Best PC Build for Software Developers & Programmers (2026)',
    metaTitle: 'Best PC Build for Programming - Docker, Rust, Linux & Full-Stack | RigCraft',
    metaDescription:
      'Fast, quiet developer desktop for software engineers. Multi-threaded compilation, 32GB/64GB RAM for Docker/Kubernetes, and quiet acoustic profile.',
    targetBudgetInr: 92000,
    targetBudgetUsd: 1100,
    categoryTag: 'Software Engineering',
    resolutionTarget: '1440p',
    primaryUseCase: 'Code Compilation, Docker Containers, Local Virtualization',
    headlineDescription:
      'Engineered for maximum developer ergonomics. Fast compilation cycles, low noise, ample RAM for Docker containers and IDEs, and instant cold-boot speeds.',
    partIds: {
      cpu: 'cpu-i5-14600k',
      gpu: 'gpu-rtx-4060-8gb',
      motherboard: 'mb-gigabyte-b760-gaming-x-ax',
      ram: 'ram-corsair-vengeance-32gb-ddr5-6000',
      storage: 'ssd-samsung-990-pro-1tb',
      psu: 'psu-corsair-rm750e-atx3',
      case: 'case-montech-air-903-max',
      cooler: 'cooler-deepcool-ak620',
    },
    componentRationale: {
      cpu: 'Core i5-13600K provides 14 cores (6P + 8E) for fast C++/Rust parallel compilation.',
      gpu: 'RTX 4060 powers multiple 4K coding monitors and offers hardware acceleration for web/game dev.',
      motherboard: 'MSI B760 Gaming Plus delivers 2.5GbE Ethernet and reliable I/O for peripherals.',
      ram: '32GB DDR5 memory ensures smooth execution of multiple IDEs, local containers, and databases.',
      storage: 'Samsung 990 Pro 1TB minimizes node_modules installation and git checkout times.',
      psu: 'Corsair RM750e ATX 3.0 runs in silent zero-RPM mode during typical coding and text editing workloads.',
      case: 'High-airflow chassis ensures silent operation without thermal throttling under build passes.',
      cooler: 'DeepCool AK620 dual-tower air cooler provides silent, maintenance-free cooling.',
    },
    upgradePaths: [
      'Add a second 2TB SSD dedicated for Linux dual-boot or heavy VM storage.',
      'Upgrade to 64GB RAM if hosting multiple Kubernetes minikubes or heavy Android emulators.',
    ],
    publishedDate: '2026-03-25',
    lastUpdatedDate: '2026-10-06',
  },
  {
    slug: 'best-pc-for-video-editing',
    title: 'Best PC Build for Video Editing & 4K Content Creation (2026)',
    metaTitle: 'Best PC for 4K Video Editing - Premiere, DaVinci Resolve & After Effects | RigCraft',
    metaDescription:
      'Optimized content creation workstation. Intel QuickSync hardware encoding, NVIDIA NVENC, 64GB DDR5 RAM, and fast scratch disk storage.',
    targetBudgetInr: 178000,
    targetBudgetUsd: 2150,
    categoryTag: 'Video Editing & VFX',
    resolutionTarget: '4K',
    primaryUseCase: '4K/8K Video Editing, Color Grading & Motion Graphics',
    headlineDescription:
      'Tailored for creators working in DaVinci Resolve, Adobe Premiere Pro, and After Effects. Harnesses Intel QuickSync and NVIDIA dual NVENC for timeline playback.',
    partIds: {
      cpu: 'cpu-i7-14700k',
      gpu: 'gpu-rtx-4070-super',
      motherboard: 'mb-asus-rog-strix-z790-e',
      ram: 'ram-crucial-pro-64gb-ddr5-5600',
      storage: 'ssd-samsung-990-pro-2tb',
      psu: 'psu-corsair-rm850x',
      case: 'case-fractal-north',
      cooler: 'cooler-arctic-freezer-iii-360',
    },
    componentRationale: {
      cpu: 'Intel i7-14700K features integrated UHD 770 graphics with Intel QuickSync, the industry standard for 4:2:2 10-bit H.264/HEVC timeline decoding.',
      gpu: 'RTX 4070 Super features 12GB VRAM and 8th Gen NVENC encoder for accelerated timeline rendering and AI denoising.',
      motherboard: 'ASUS TUF Z790-Plus provides USB 3.2 Gen 2x2 Type-C for external camera card readers and SSD docks.',
      ram: '64GB DDR5 memory allows smooth timeline caching and After Effects RAM previews.',
      storage: 'Samsung 990 Pro 2TB handles uncompressed 4K ProRes footage without dropped frames.',
      psu: 'Corsair RM850x delivers clean power under sustained CPU and GPU rendering loads.',
      case: 'Fractal North with mesh side provides quiet acoustic dampening for audio editing studios.',
      cooler: 'Arctic Liquid Freezer III 360 keeps the 253W Intel boost envelope cool during long exports.',
    },
    upgradePaths: [
      'Add dedicated high-capacity SATA HDDs or a NAS for long-term project archiving.',
      'Upgrade to RTX 4080 Super or 4090 if regularly rendering complex 3D VFX in Blender or Cinema 4D.',
    ],
    publishedDate: '2026-04-01',
    lastUpdatedDate: '2026-10-06',
  },
]

export function getSeoBuildBySlug(slug: string): SeoBuildPage | undefined {
  return SEO_BUILDS.find((b) => b.slug === slug)
}
